#!/usr/bin/env bash

set -e 

rm -rf build dist
wasm-pack build --target bundler --out-name index --out-dir build --release
wasm2js build/index_bg.wasm -o build/index_bg.js
sed -i 's/import . as wasm from ...index_bg.wasm./var wasm = null/' build/index.js
echo "export const _setwasm = (w) => { wasm = w };" >> build/index.js
echo "import * as wasm from './index_bg.js';" > build/bond.js
echo "import { _setwasm } from './index.js';" >> build/bond.js
echo "_setwasm(wasm);" >> build/bond.js
echo "export * from './index.js';" >> build/bond.js
cp index.js build/entry.js
sed -i 's/build/bond/' build/entry.js
$(npm bin)/webpack
cp package.json README.md LICENSE dist
sed -i 's/automerge-backend-wasm/automerge-backend-asmjs/' dist/package.json
rm -rf build
