#!/usr/bin/env bash

set -e 

rm -rf pkg dist
wasm-pack build --target bundler --out-name index --release
cp index-async.js pkg/entry.js
sed -i 's/pkg/index/' pkg/entry.js
$(npm bin)/webpack
cp package.json README.md LICENSE dist
sed -i 's/automerge-backend-wasm/automerge-backend-wasm-async/' dist/package.json
rm -rf pkg
