#!/usr/bin/env bash
set -eoux pipefail

cd rust
cargo deny --version
if [ "$#" -gt 0 ]; then
    cargo deny check "$@"
else
    cargo deny check advisories
    cargo deny check licenses
    cargo deny check bans
    cargo deny check sources
fi
