#!/usr/bin/env bash

set -eoux pipefail

mkdir -p crates/automerge-c/build
cd rust/automerge-c/build
cmake -B . -S .. -DBUILD_TESTING=OFF
cmake --build . --target automerge_docs

echo "Try opening crates/automerge-c/build/src/html/index.html"
