#!/usr/bin/env bash

set -eoux pipefail

mkdir -p automerge-c/build
cd automerge-c/build
cmake -B . -S ..
cmake --build . --target automerge_docs

echo "Try opening automerge-c/build/src/html/index.html"
