#!/usr/bin/env bash
set -eoux pipefail

# see https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
THIS_SCRIPT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
yarn --cwd $THIS_SCRIPT/../../javascript install
yarn --cwd $THIS_SCRIPT/../../javascript prettier -v
