#!/usr/bin/env bash
set -eoux pipefail

# see https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
THIS_SCRIPT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
JS_PROJECT=$THIS_SCRIPT/../../javascript;

yarn --cwd $JS_PROJECT install
node $JS_PROJECT/scripts/build.mjs
yarn --cwd $JS_PROJECT test
yarn --cwd $JS_PROJECT packaging-tests
