#!/usr/bin/env bash
set -eoux pipefail

# see https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
THIS_SCRIPT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
WASM_PROJECT=$THIS_SCRIPT/../../rust/automerge-wasm;
JS_PROJECT=$THIS_SCRIPT/../../javascript;
E2E_PROJECT=$THIS_SCRIPT/../../javascript/e2e;

yarn --cwd $E2E_PROJECT install;
# This will build the automerge-wasm project, publish it to a local NPM
# repository, then run `yarn build` in the `javascript` directory with
# the local registry
yarn --cwd $E2E_PROJECT e2e buildjs;
yarn --cwd $JS_PROJECT check-fmt
yarn --cwd $JS_PROJECT test
