#!/usr/bin/env bash
set -eoux pipefail

# Force clippy to consider all local sources
# https://github.com/rust-lang/rust-clippy/issues/4612
find . -name "*.rs" -not -path "./target/*" -exec touch "{}" +
cargo clippy --all-targets -- -D warnings
cargo clippy -p automerge --features storage-v2
