#!/usr/bin/env bash
set -eou pipefail

./scripts/ci/fmt
./scripts/ci/fmt_js
./scripts/ci/lint
./scripts/ci/build-test
./scripts/ci/rust-docs
./scripts/ci/advisory
./scripts/ci/wasm_tests
./scripts/ci/js_tests
./scripts/ci/node_18_packaging_test
./scripts/ci/cmake-build Release static
