#!/usr/bin/env bash
set -eou pipefail

./scripts/ci/fmt
./scripts/ci/lint
./scripts/ci/build-test
./scripts/ci/docs
./scripts/ci/advisory
./scripts/ci/wasm_tests
./scripts/ci/js_tests
./scripts/ci/cmake-build Release static
