#ifndef automerge_h
#define automerge_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdbool.h>

typedef struct Backend Backend;

/**
 * A byte buffer
 */
typedef struct {
  /**
   * A pointer to the bytes
   */
  uint8_t *data;
  /**
   * The number of bytes
   */
  uintptr_t data_len;
} Buffer;

/**
 * # Safety
 * This should be called with a valid backend pointer
 * and valid out pointers
 */
intptr_t automerge_apply_local_change(Backend *backend, const uint8_t *request, uintptr_t len, Buffer **change_buf, Buffer **json_buf);

/**
 * # Safety
 * This must be called with a valid backend pointer
 */
void automerge_free(Backend *backend);

Backend *automerge_init(void);

#endif /* automerge_h */
