[package]
name = "packer"
version = "0.1.0"
edition = "2021"

[dependencies]
leb128 = "^0.2.5"
thiserror = "^1.0.16"

[dev-dependencies]
proptest = { version = "^1.0.0", default-features = false, features = ["std"] }
rand = { version = "^0.8.4", optional = false, features = [ "small_rng"] }
