#ifndef automerge_h
#define automerge_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdbool.h>

typedef struct Backend Backend;

typedef struct {
  uintptr_t len;
  uintptr_t cap;
  uint8_t *ptr;
} Change;

typedef struct {
  uintptr_t len;
  uintptr_t cap;
  Change *ptr;
} Changes;

typedef struct {
  uintptr_t len;
  uintptr_t cap;
  uint8_t *ptr;
} Document;

const char *automerge_apply_changes(Backend *backend, uintptr_t num_changes, const Change *changes);

const char *automerge_apply_local_change(Backend *backend, const char *request);

Backend *automerge_clone(Backend *backend);

void automerge_free(Backend *backend);

void automerge_free_change(Change *change);

void automerge_free_changes(Changes *changes);

void automerge_free_document(Document *doc);

void automerge_free_string(const char *string);

const Changes *automerge_get_changes(Backend *backend, uintptr_t len, const uint8_t *binary);

const Changes *automerge_get_changes_for_actor(Backend *backend, const char *actor);

const char *automerge_get_missing_deps(Backend *backend);

const char *automerge_get_patch(Backend *backend);

Backend *automerge_init(void);

Backend *automerge_load(uintptr_t len, const uint8_t *binary);

void automerge_load_changes(Backend *backend, uintptr_t num_changes, const Change *changes);

const Document *automerge_save(Backend *backend);

#endif /* automerge_h */
