name: Advisories
on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-cargo-deny -- ${{ matrix.checks }}
