name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-lint

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Build Rust docs
        run: nix run .#ci-rust-docs

  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-cargo-deny -- ${{ matrix.checks }}

  build_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Run WASM tests
        run: nix run .#ci-wasm-tests

  js_tests:
    runs-on: ubuntu-latest
    needs:
      - build_wasm
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Run JS tests
        run: nix run .#ci-js-tests

  # This test is necessary because we want to make sure that the webcrypto polyfill
  # for node 18 works correctly. See the notes in javascript/HACKING.md#getrandom-support
  node_18_packaging_test:
    runs-on: ubuntu-latest
    needs:
      - build_wasm
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Run Node 18 packaging test
        run: nix run .#ci-node18-packaging-test

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-build-test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix run .#ci-build-test

  # Nix does not provide a native Windows environment. Keep this job native so
  # that it continues to test Windows rather than Linux under WSL.
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/ci/build-test
        shell: bash
