name: Release
on:
  release:
    types: [published]

jobs:
  publish-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Build JS package
        run: nix run .#release-js-build
      - name: Configure npm authentication
        run: |
          printf '%s\n' "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" \
            > "$RUNNER_TEMP/.npmrc"
      - name: "npm publish pre-release"
        if: github.event.release.prerelease
        run: nix run .#release-js-publish -- --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ runner.temp }}/.npmrc
      - name: "npm publish release"
        if: "!github.event.release.prerelease"
        run: nix run .#release-js-publish -- --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ runner.temp }}/.npmrc

  publish-js-docs:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Build JS docs
        run: nix run .#release-js-docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./javascript/api-docs
          target-folder: api-docs/js
